include:
  - vpn-docker-compose.yaml
  - qbittorrent-docker-compose.yaml
services:
  qbittorrent-multiplexer:
    container_name: qbittorrent-multiplexer
    network_mode: "container:${VPN_SERVICE_NAME}"
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      MULTIPLEXER_PORT: ${MULTIPLEXER_PORT}
    volumes:
      - ./config.yaml.example:/root/config.yaml
    build: .
    develop:
      watch:
        - action: rebuild
          path: ./